In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('car_purchasing.csv', encoding='cp1252')

In [3]:
df.head()

,customer name,customer e-mail,country,gender,age,annual Salary,credit card debt,net worth,car purchase amount
0,Martina Avila,cubilia.Curae.Phasellus@quisaccumsanconvallis.edu,Bulgaria,0,41.851720,62812.09301,11609.380910,238961.2505,35321.45877
1,Harlan Barnes,eu.dolor@diam.co.uk,Belize,0,40.870623,66646.89292,9572.957136,530973.9078,45115.52566
2,Naomi Rodriquez,vulputate.mauris.sagittis@ametconsectetueradip...,Algeria,1,43.152897,53798.55112,11160.355060,638467.1773,42925.70921
3,Jade Cunningham,malesuada@dignissim.com,Cook Islands,1,58.271369,79370.03798,14426.164850,548599.0524,67422.36313
4,Cedric Leach,felis.ullamcorper.viverra@egetmollislectus.net,Brazil,1,57.313749,59729.15130,5358.712177,560304.0671,55915.46248

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer name        500 non-null    str
 1   customer e-mail      500 non-null    str
 2   country              500 non-null    str
 3   gender               500 non-null    int64
 4   age                  500 non-null    float64
 5   annual Salary        500 non-null    float64
 6   credit card debt     500 non-null    float64
 7   net worth            500 non-null    float64
 8   car purchase amount  500 non-null    float64
dtypes: float64(5), int64(1), str(3)
memory usage: 35.3 KB

In [5]:
# Weird gender mapping male -> 0, female -> 1

In [6]:
# Customer_name + customer_email dropped

In [7]:
# OridinalEncoder country

In [8]:
gender_fix_map = {
    0: "Male",
    1: "Female"
}

In [9]:
df["gender"] = df["gender"].map(gender_fix_map)

In [10]:
gender_map = {
    "Female": 0,
    "Male": 1
}

In [11]:
df["gender"] = df["gender"].map(gender_map)

In [12]:
# Age is weird also I will use floor for that

In [13]:
df["age"] = np.floor(df["age"])

In [14]:
df["age"]

0      41.0
1      40.0
2      43.0
3      58.0
4      57.0
       ...
495    41.0
496    37.0
497    53.0
498    59.0
499    46.0
Name: age, Length: 500, dtype: float64

In [15]:
df["age"] = df["age"].astype("int64")

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer name        500 non-null    str
 1   customer e-mail      500 non-null    str
 2   country              500 non-null    str
 3   gender               500 non-null    int64
 4   age                  500 non-null    int64
 5   annual Salary        500 non-null    float64
 6   credit card debt     500 non-null    float64
 7   net worth            500 non-null    float64
 8   car purchase amount  500 non-null    float64
dtypes: float64(4), int64(2), str(3)
memory usage: 35.3 KB

In [17]:
df = df.drop(["customer name","customer e-mail"],axis=1)

In [18]:
df

,country,gender,age,annual Salary,credit card debt,net worth,car purchase amount
0,Bulgaria,1,41,62812.09301,11609.380910,238961.2505,35321.45877
1,Belize,1,40,66646.89292,9572.957136,530973.9078,45115.52566
2,Algeria,0,43,53798.55112,11160.355060,638467.1773,42925.70921
3,Cook Islands,0,58,79370.03798,14426.164850,548599.0524,67422.36313
4,Brazil,0,57,59729.15130,5358.712177,560304.0671,55915.46248
...,...,...,...,...,...,...,...
495,Nepal,1,41,71942.40291,6995.902524,541670.1016,48901.44342
496,Zimbabwe,0,37,56039.49793,12301.456790,360419.0988,31491.41457
497,Philippines,0,53,68888.77805,10611.606860,764531.3203,64147.28888
498,Botswana,0,59,49811.99062,14013.034510,337826.6382,45442.15353
499,marlal,0,46,61370.67766,9391.341628,462946.4924,45107.22566

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X = df.drop("car purchase amount",axis=1)
y = df["car purchase amount"]

In [21]:
X_temp,X_test,y_temp,y_test = train_test_split(X,y,test_size=0.15,random_state=15)

In [22]:
X_train, X_val, y_train, y_val = train_test_split(
    X_temp, y_temp,
    test_size=0.17647, # Train -> 70 , test -> 15 , validation = 15
    random_state=15
)

In [23]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

categorical_cols = ["country"]

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore", sparse_output=False), categorical_cols)
    ],
    remainder="passthrough"
)

X_train = preprocessor.fit_transform(X_train)
X_val = preprocessor.transform(X_val)
X_test = preprocessor.transform(X_test)

In [24]:
X_train

array([[     0.      ,      0.      ,      0.      , ...,  69248.4953  ,
          6445.784981, 298246.0609  ],
       [     0.      ,      0.      ,      0.      , ...,  32697.98161 ,
         10858.02526 , 218808.7553  ],
       [     0.      ,      0.      ,      0.      , ...,  67015.19372 ,
         13000.41369 , 355157.6417  ],
       ...,
       [     0.      ,      0.      ,      0.      , ...,  84467.78988 ,
          7772.444847, 468238.7915  ],
       [     0.      ,      0.      ,      0.      , ...,  60382.17885 ,
         11302.88277 , 490444.4111  ],
       [     0.      ,      0.      ,      0.      , ...,  46549.16329 ,
           640.045378, 626163.832   ]], shape=(350, 190))

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
scaler = StandardScaler()

In [27]:
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

In [28]:
import tensorflow as tf

In [29]:
from tensorflow.keras.layers import Input,Dense,Dropout

In [30]:
from tensorflow.keras.models import Sequential

In [31]:
model = Sequential()

In [32]:
model.add(Input(shape=(190,)))
model.add(Dense(32,activation="relu"))
model.add(Dropout(0.3))
model.add(Dense(16,activation="relu"))
model.add(Dropout(0.25))
model.add(Dense(1))

In [33]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 32)                  │           6,112 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 32)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 16)                  │             528 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 16)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              17 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 6,657 (26.00 KB)

 Trainable params: 6,657 (26.00 KB)

 Non-trainable params: 0 (0.00 B)

In [34]:
model.compile(
    optimizer='adam',
    loss='mse',
    metrics=["mse"]
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [35]:
from tensorflow.keras.callbacks import EarlyStopping

In [36]:
early_stopping = EarlyStopping(
    monitor="val_loss",
    patience=10,
    restore_best_weights=True
)

In [37]:
history = model.fit(
    X_train,
    y_train,
    validation_data=(X_val, y_val),
    epochs=10000,
    batch_size=32,
    callbacks=[early_stopping]
)

Epoch 1/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 5s 83ms/step - loss: 2089333504.0000 - mse: 2089333504.0000 - val_loss: 1945240448.0000 - val_mse: 1945240448.0000
Epoch 2/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 2089276416.0000 - mse: 2089276416.0000 - val_loss: 1945191680.0000 - val_mse: 1945191680.0000
Epoch 3/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 2089225088.0000 - mse: 2089225088.0000 - val_loss: 1945137536.0000 - val_mse: 1945137536.0000
Epoch 4/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 2089158528.0000 - mse: 2089158528.0000 - val_loss: 1945072256.0000 - val_mse: 1945072256.0000
Epoch 5/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 2089081088.0000 - mse: 2089081088.0000 - val_loss: 1944989824.0000 - val_mse: 1944989824.0000
Epoch 6/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 2088995328.0000 - mse: 2088995328.0000 - val_loss: 1944886144.0000 - val_mse: 1944886272.0000
Epoch 7/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 2088864512.0000 - mse: 2088864512.0000 - val_loss: 1944752384.0000 - val_mse: 1944752384.0000
Epoch 8/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 2088716800.0000 - mse: 2088716800.0000 - val_loss: 1944581632.0000 - val_mse: 1944581632.0000
Epoch 9/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 2088493696.0000 - mse: 2088493696.0000 - val_loss: 1944368384.0000 - val_mse: 1944368384.0000
Epoch 10/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 2088301056.0000 - mse: 2088301056.0000 - val_loss: 1944107136.0000 - val_mse: 1944107136.0000
Epoch 11/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 2088012160.0000 - mse: 2088012160.0000 - val_loss: 1943792256.0000 - val_mse: 1943792256.0000
Epoch 12/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 2087626624.0000 - mse: 2087626624.0000 - val_loss: 1943413248.0000 - val_mse: 1943413248.0000
Epoch 13/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 2087220864.0000 - mse: 2087220864.0000 - val_loss: 1942953600.0000 - val_mse: 1942953600.0000
Epoch 14/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 2086756992.0000 - mse: 2086756992.0000 - val_loss: 1942419712.0000 - val_mse: 1942419712.0000
Epoch 15/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 2086100224.0000 - mse: 2086100224.0000 - val_loss: 1941788160.0000 - val_mse: 1941788160.0000
Epoch 16/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 2085649664.0000 - mse: 2085649664.0000 - val_loss: 1941050496.0000 - val_mse: 1941050496.0000
Epoch 17/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 2084818176.0000 - mse: 2084818176.0000 - val_loss: 1940218880.0000 - val_mse: 1940218880.0000
Epoch 18/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 2083865216.0000 - mse: 2083865216.0000 - val_loss: 1939263360.0000 - val_mse: 1939263360.0000
Epoch 19/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - loss: 2082676224.0000 - mse: 2082676224.0000 - val_loss: 1938173184.0000 - val_mse: 1938173184.0000
Epoch 20/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 2081749120.0000 - mse: 2081749120.0000 - val_loss: 1936922752.0000 - val_mse: 1936922752.0000
Epoch 21/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 2080347776.0000 - mse: 2080347776.0000 - val_loss: 1935496320.0000 - val_mse: 1935496320.0000
Epoch 22/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 2079007872.0000 - mse: 2079007872.0000 - val_loss: 1933900032.0000 - val_mse: 1933900032.0000
Epoch 23/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 2077065984.0000 - mse: 2077065984.0000 - val_loss: 1932120064.0000 - val_mse: 1932120064.0000
Epoch 24/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 2075157376.0000 - mse: 2075157376.0000 - val_loss: 1930085504.0000 - val_mse: 1930085504.0000
Epoch 25/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 2073453440.0000 - mse: 2073453440.0000 - val_loss: 1927871232.0000 - val_mse: 1927871232.0000
Epoch 26/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 2071177088.0000 - mse: 2071177088.0000 - val_loss: 1925462272.0000 - val_mse: 1925462272.0000
Epoch 27/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 2068579456.0000 - mse: 2068579456.0000 - val_loss: 1922821632.0000 - val_mse: 1922821632.0000
Epoch 28/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 2065555840.0000 - mse: 2065555840.0000 - val_loss: 1919937152.0000 - val_mse: 1919937152.0000
Epoch 29/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 2062156160.0000 - mse: 2062156160.0000 - val_loss: 1916718976.0000 - val_mse: 1916718976.0000
Epoch 30/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 2059323648.0000 - mse: 2059323648.0000 - val_loss: 1913291136.0000 - val_mse: 1913291136.0000
Epoch 31/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 2056254336.0000 - mse: 2056254336.0000 - val_loss: 1909604096.0000 - val_mse: 1909604096.0000
Epoch 32/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 2053112192.0000 - mse: 2053112192.0000 - val_loss: 1905753216.0000 - val_mse: 1905753216.0000
Epoch 33/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 2048401280.0000 - mse: 2048401280.0000 - val_loss: 1901587712.0000 - val_mse: 1901587712.0000
Epoch 34/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - loss: 2043477504.0000 - mse: 2043477504.0000 - val_loss: 1897064064.0000 - val_mse: 1897064064.0000
Epoch 35/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 2039208576.0000 - mse: 2039208576.0000 - val_loss: 1892253056.0000 - val_mse: 1892253056.0000
Epoch 36/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 2035381504.0000 - mse: 2035381504.0000 - val_loss: 1887193472.0000 - val_mse: 1887193472.0000
Epoch 37/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 2029867136.0000 - mse: 2029867136.0000 - val_loss: 1881876352.0000 - val_mse: 1881876352.0000
Epoch 38/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 2024376192.0000 - mse: 2024376192.0000 - val_loss: 1876179840.0000 - val_mse: 1876179840.0000
Epoch 39/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 2017940352.0000 - mse: 2017940096.0000 - val_loss: 1870253312.0000 - val_mse: 1870253312.0000
Epoch 40/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 2011552640.0000 - mse: 2011552640.0000 - val_loss: 1863864320.0000 - val_mse: 1863864320.0000
Epoch 41/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 2004983424.0000 - mse: 2004983424.0000 - val_loss: 1857193728.0000 - val_mse: 1857193728.0000
Epoch 42/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 1999254272.0000 - mse: 1999254272.0000 - val_loss: 1850219392.0000 - val_mse: 1850219392.0000
Epoch 43/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 1994045696.0000 - mse: 1994045696.0000 - val_loss: 1842972544.0000 - val_mse: 1842972544.0000
Epoch 44/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 1986425728.0000 - mse: 1986425728.0000 - val_loss: 1835470720.0000 - val_mse: 1835470720.0000
Epoch 45/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 1977256320.0000 - mse: 1977256320.0000 - val_loss: 1827602688.0000 - val_mse: 1827602688.0000
Epoch 46/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 1968648064.0000 - mse: 1968648064.0000 - val_loss: 1819301120.0000 - val_mse: 1819301120.0000
Epoch 47/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 1961408256.0000 - mse: 1961408256.0000 - val_loss: 1810730496.0000 - val_mse: 1810730496.0000
Epoch 48/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 1954236160.0000 - mse: 1954236160.0000 - val_loss: 1801815552.0000 - val_mse: 1801815552.0000
Epoch 49/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1945649280.0000 - mse: 1945649280.0000 - val_loss: 1792707200.0000 - val_mse: 1792707200.0000
Epoch 50/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 1935085056.0000 - mse: 1935085056.0000 - val_loss: 1783037568.0000 - val_mse: 1783037568.0000
Epoch 51/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 1927802624.0000 - mse: 1927802624.0000 - val_loss: 1773183104.0000 - val_mse: 1773183104.0000
Epoch 52/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1916096128.0000 - mse: 1916096128.0000 - val_loss: 1763002240.0000 - val_mse: 1763002240.0000
Epoch 53/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 1903703168.0000 - mse: 1903703168.0000 - val_loss: 1752316416.0000 - val_mse: 1752316416.0000
Epoch 54/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1893254144.0000 - mse: 1893254144.0000 - val_loss: 1741238656.0000 - val_mse: 1741238656.0000
Epoch 55/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 1888859136.0000 - mse: 1888859136.0000 - val_loss: 1729964416.0000 - val_mse: 1729964416.0000
Epoch 56/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 1865866496.0000 - mse: 1865866496.0000 - val_loss: 1718208896.0000 - val_mse: 1718208896.0000
Epoch 57/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1864280832.0000 - mse: 1864280832.0000 - val_loss: 1706078592.0000 - val_mse: 1706078592.0000
Epoch 58/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 1848412672.0000 - mse: 1848412672.0000 - val_loss: 1693718784.0000 - val_mse: 1693718784.0000
Epoch 59/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1836390272.0000 - mse: 1836390272.0000 - val_loss: 1681048576.0000 - val_mse: 1681048576.0000
Epoch 60/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 1821908096.0000 - mse: 1821908096.0000 - val_loss: 1667881088.0000 - val_mse: 1667881088.0000
Epoch 61/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 1814735872.0000 - mse: 1814735872.0000 - val_loss: 1654647296.0000 - val_mse: 1654647296.0000
Epoch 62/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 1795722112.0000 - mse: 1795722112.0000 - val_loss: 1640864768.0000 - val_mse: 1640864768.0000
Epoch 63/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - loss: 1783923072.0000 - mse: 1783923072.0000 - val_loss: 1626875904.0000 - val_mse: 1626875904.0000
Epoch 64/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 1773288192.0000 - mse: 1773288192.0000 - val_loss: 1612466688.0000 - val_mse: 1612466688.0000
Epoch 65/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 1756614272.0000 - mse: 1756614272.0000 - val_loss: 1597830016.0000 - val_mse: 1597830016.0000
Epoch 66/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1736990080.0000 - mse: 1736990080.0000 - val_loss: 1582860160.0000 - val_mse: 1582860160.0000
Epoch 67/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1727426944.0000 - mse: 1727426944.0000 - val_loss: 1567265920.0000 - val_mse: 1567265920.0000
Epoch 68/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1714301952.0000 - mse: 1714301952.0000 - val_loss: 1551779968.0000 - val_mse: 1551779968.0000
Epoch 69/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 1708163968.0000 - mse: 1708163968.0000 - val_loss: 1536081920.0000 - val_mse: 1536081920.0000
Epoch 70/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 1674162432.0000 - mse: 1674162432.0000 - val_loss: 1519847424.0000 - val_mse: 1519847424.0000
Epoch 71/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 1667533568.0000 - mse: 1667533568.0000 - val_loss: 1503574784.0000 - val_mse: 1503574784.0000
Epoch 72/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 1644392064.0000 - mse: 1644392064.0000 - val_loss: 1486719744.0000 - val_mse: 1486719744.0000
Epoch 73/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1624719872.0000 - mse: 1624719872.0000 - val_loss: 1469580416.0000 - val_mse: 1469580416.0000
Epoch 74/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 1611625728.0000 - mse: 1611625728.0000 - val_loss: 1452229504.0000 - val_mse: 1452229504.0000
Epoch 75/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 1598691968.0000 - mse: 1598691968.0000 - val_loss: 1434497024.0000 - val_mse: 1434497024.0000
Epoch 76/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 1587258368.0000 - mse: 1587258368.0000 - val_loss: 1416863232.0000 - val_mse: 1416863232.0000
Epoch 77/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1570902656.0000 - mse: 1570902656.0000 - val_loss: 1399203200.0000 - val_mse: 1399203200.0000
Epoch 78/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1543707648.0000 - mse: 1543707648.0000 - val_loss: 1380965632.0000 - val_mse: 1380965632.0000
Epoch 79/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 1525639040.0000 - mse: 1525639040.0000 - val_loss: 1362252672.0000 - val_mse: 1362252672.0000
Epoch 80/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 1514557568.0000 - mse: 1514557568.0000 - val_loss: 1343821312.0000 - val_mse: 1343821312.0000
Epoch 81/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 1494040704.0000 - mse: 1494040704.0000 - val_loss: 1325088896.0000 - val_mse: 1325088896.0000
Epoch 82/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1472963200.0000 - mse: 1472963200.0000 - val_loss: 1306037120.0000 - val_mse: 1306037120.0000
Epoch 83/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 1444073216.0000 - mse: 1444073216.0000 - val_loss: 1286685568.0000 - val_mse: 1286685568.0000
Epoch 84/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 1435990144.0000 - mse: 1435990144.0000 - val_loss: 1267149824.0000 - val_mse: 1267149824.0000
Epoch 85/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 1413004032.0000 - mse: 1413004032.0000 - val_loss: 1247604352.0000 - val_mse: 1247604352.0000
Epoch 86/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 1413950720.0000 - mse: 1413950720.0000 - val_loss: 1228125952.0000 - val_mse: 1228125952.0000
Epoch 87/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1383691136.0000 - mse: 1383691136.0000 - val_loss: 1208444544.0000 - val_mse: 1208444544.0000
Epoch 88/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 1350421888.0000 - mse: 1350421888.0000 - val_loss: 1188629760.0000 - val_mse: 1188629760.0000
Epoch 89/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1335194496.0000 - mse: 1335194496.0000 - val_loss: 1168474368.0000 - val_mse: 1168474368.0000
Epoch 90/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 1318964864.0000 - mse: 1318964864.0000 - val_loss: 1148098688.0000 - val_mse: 1148098688.0000
Epoch 91/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 1300213120.0000 - mse: 1300213120.0000 - val_loss: 1128041728.0000 - val_mse: 1128041728.0000
Epoch 92/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1280641536.0000 - mse: 1280641536.0000 - val_loss: 1107943424.0000 - val_mse: 1107943424.0000
Epoch 93/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 1247986816.0000 - mse: 1247986816.0000 - val_loss: 1087436288.0000 - val_mse: 1087436288.0000
Epoch 94/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 1246476800.0000 - mse: 1246476800.0000 - val_loss: 1067278016.0000 - val_mse: 1067278016.0000
Epoch 95/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1205258752.0000 - mse: 1205258752.0000 - val_loss: 1046785792.0000 - val_mse: 1046785792.0000
Epoch 96/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 1209261184.0000 - mse: 1209261184.0000 - val_loss: 1026271040.0000 - val_mse: 1026271040.0000
Epoch 97/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1177969024.0000 - mse: 1177969024.0000 - val_loss: 1005944512.0000 - val_mse: 1005944512.0000
Epoch 98/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 1157003136.0000 - mse: 1157003136.0000 - val_loss: 985319424.0000 - val_mse: 985319424.0000
Epoch 99/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1146224384.0000 - mse: 1146224384.0000 - val_loss: 964896448.0000 - val_mse: 964896448.0000
Epoch 100/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 1112450304.0000 - mse: 1112450304.0000 - val_loss: 944691072.0000 - val_mse: 944691072.0000
Epoch 101/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 1097932032.0000 - mse: 1097932032.0000 - val_loss: 924477824.0000 - val_mse: 924477824.0000
Epoch 102/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 1072889472.0000 - mse: 1072889472.0000 - val_loss: 904039424.0000 - val_mse: 904039424.0000
Epoch 103/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 1058158272.0000 - mse: 1058158272.0000 - val_loss: 884063168.0000 - val_mse: 884063168.0000
Epoch 104/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 1043048704.0000 - mse: 1043048704.0000 - val_loss: 863983232.0000 - val_mse: 863983232.0000
Epoch 105/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1020002304.0000 - mse: 1020002304.0000 - val_loss: 843758656.0000 - val_mse: 843758656.0000
Epoch 106/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 987419008.0000 - mse: 987419008.0000 - val_loss: 824048256.0000 - val_mse: 824048256.0000
Epoch 107/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 955685952.0000 - mse: 955685952.0000 - val_loss: 804043904.0000 - val_mse: 804043904.0000
Epoch 108/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 946901504.0000 - mse: 946901504.0000 - val_loss: 784089024.0000 - val_mse: 784089024.0000
Epoch 109/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 921290112.0000 - mse: 921290112.0000 - val_loss: 764366272.0000 - val_mse: 764366272.0000
Epoch 110/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 913071808.0000 - mse: 913071808.0000 - val_loss: 745207040.0000 - val_mse: 745207040.0000
Epoch 111/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 878193792.0000 - mse: 878193792.0000 - val_loss: 725901120.0000 - val_mse: 725901120.0000
Epoch 112/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 863769152.0000 - mse: 863769152.0000 - val_loss: 706955712.0000 - val_mse: 706955712.0000
Epoch 113/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 842771520.0000 - mse: 842771520.0000 - val_loss: 688042048.0000 - val_mse: 688042048.0000
Epoch 114/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 850667968.0000 - mse: 850667968.0000 - val_loss: 669352000.0000 - val_mse: 669352000.0000
Epoch 115/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 809452672.0000 - mse: 809452672.0000 - val_loss: 651204992.0000 - val_mse: 651204992.0000
Epoch 116/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 803490752.0000 - mse: 803490752.0000 - val_loss: 633177280.0000 - val_mse: 633177280.0000
Epoch 117/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 780965568.0000 - mse: 780965568.0000 - val_loss: 615235712.0000 - val_mse: 615235712.0000
Epoch 118/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 732629376.0000 - mse: 732629376.0000 - val_loss: 597526016.0000 - val_mse: 597526016.0000
Epoch 119/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 732759488.0000 - mse: 732759488.0000 - val_loss: 580209408.0000 - val_mse: 580209408.0000
Epoch 120/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 718711296.0000 - mse: 718711296.0000 - val_loss: 563124608.0000 - val_mse: 563124608.0000
Epoch 121/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - loss: 698842432.0000 - mse: 698842432.0000 - val_loss: 546372096.0000 - val_mse: 546372096.0000
Epoch 122/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 696346368.0000 - mse: 696346368.0000 - val_loss: 529917984.0000 - val_mse: 529917984.0000
Epoch 123/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 706401984.0000 - mse: 706401984.0000 - val_loss: 513661824.0000 - val_mse: 513661824.0000
Epoch 124/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 626080128.0000 - mse: 626080128.0000 - val_loss: 497836032.0000 - val_mse: 497836032.0000
Epoch 125/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 618498560.0000 - mse: 618498560.0000 - val_loss: 482268128.0000 - val_mse: 482268128.0000
Epoch 126/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 623010432.0000 - mse: 623010432.0000 - val_loss: 466973600.0000 - val_mse: 466973600.0000
Epoch 127/10000
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 571823296.0000 - mse: 571823296.0000 - val_loss: 452113696.0000 - val_mse: 452113696.0000
Epoch 128/10000